baseurl = "/"
title = "Klimawatch"
author = "Code for Germany"
enableRobotsTXT = true
defaultContentLanguage = "de"
language = "de-de"
paginate = 3

theme = "piercer"

[privacy]
    [privacy.twitter]
        disable = false
        enableDNT = true
        simple = false

[params]
    description = "Piercer is a fast and customizable theme for Hugo. Designed with a mobile-first philosophy and with accessibility in mind."
    favicon = "/img/favicon.ico"
    logo = "/img/klimawatch_gruen.png"

[params.postcss]
    postcss = false

[params.palette]
    text = "#BEBEBE" # was: "#fdfdfd"
    background = "#FFFFFF" # was: "#282a36"
    accent = "#01873B" # was :"#44475a"
    foreground = "#000000" #was: "#f8f8f2"
    separator = "#6272a4"
    cyan = "#8be9fd"
    green = "#50fa7b"
    orange = "#ffb86c"
    pink = "#01873B" # was: "#ff79c6"
    purple = "#bd93f9"
    red = "#ff5555"
    yellow = "#f1fa8c"

[params.fontsizes]
    base = "1em"
    p = "1.25em"
    h4 = "1.563em"
    h3 = "1.953em"
    h2 = "2.441em"
    h1 = "3.052em"

[params.googlefonts]
    font = "Open Sans"

[params.serviceWorker]
    enable = true

[params.header]
    show = true

[params.cta]
    show = true
    message = "Zeig mir meine Kommune!"
    link = "/kommunen/liste/"

[params.fa]
    disable = false
    kit = ""

[params.form]
    show = false
    netlify = false
    action = ""
    method = "POST"
    section = "Contact me!"
    disclaimer = "Elit anim sit labore tempor exercitation in ad cupidatat."
    inputNameName = "Name"
    inputNameLabel = "Name"
    inputNamePlaceholder = "Your Name"
    inputEmailName = "Email"
    inputEmailLabel = "Email"
    inputEmailPlaceholder = "Your Email"
    SubmitValue = ""

[params.contact]
    show = true
    email = "example@hugo.com"
    #phone = "123456789+"
    #skype = "live:example"
    #address = "P. Sherman 42, Wallaby Way, Sydney"

[params.date]
    format = ""

[params.social]
    twitter = "#"
    facebook = "#"
    github = "#"
    gitlab = "#"
    codepen = "#"
    instagram = "#"
    pinterest = "#"
    youtube = "#"
    linkedin = ""
    weibo = ""
    mastodon = ""
    tumblr = ""
    flickr = ""
    "500px" = ""
    rss = "#"

[params.copy]
    message = ""

[params.agreement]
    message = "TODO: Footersachen."

[params.notfound]
    message = ""
